// var roomsImgUrls = [];

var roomsImgUrls = [
		"<img data-name='LAGOON SIDE ROOM' data-description='Preferred by couples and smaller families who want to be close to the lagoon. Our most popular room.' src='./pbayImages/Pictures/rooms/LagoonSideRoom.jpg' />",
		"<img data-name='LAGOON SIDE ROOM' data-description='Preferred by couples and smaller families who want to be close to the lagoon. Our most popular room.' src='./pbayImages/Pictures/rooms/LagoonSideTerrace.jpg' />",
		"<img data-name='LAGOON VIEW ROOM' data-description='Exactly the same room and amenities as a Lagoon Side room, with a better view in fact, but just a little farther from the lagoon.' src='./pbayImages/Pictures/rooms/LagoonViewRoom.jpg' />",
		"<img data-name='LAGOON VIEW ROOM' data-description='Exactly the same room and amenities as a Lagoon Side room, with a better view in fact, but just a little farther from the lagoon.' src='./pbayImages/Pictures/rooms/LagoonViewTerrace.jpg' />",
		"<img data-name='ONE BEDROOM SUITE' data-description='For parents with one or two older children, or executives who need space to work or entertain.' src='./pbayImages/Pictures/rooms/OneBedroomSuite.jpg' />",
		"<img data-name='ONE BEDROOM SUITE' data-description='For parents with one or two older children, or executives who need space to work or entertain.' src='./pbayImages/Pictures/rooms/OneBedroomSuite2.jpg' />",
		"<img data-name='ONE BEDROOM SUITE' data-description='For parents with one or two older children, or executives who need space to work or entertain.' src='./pbayImages/Pictures/rooms/OneBedroomSuite3.jpg' />",
		"<img data-name='POOLSIDE ROOM' data-description='The #1 choice of smart shoppers - spacious and comfortable (sleeps 2 adults and 2 children), great for making new friends, and $60 less than the Waters Edge room' src='./pbayImages/Pictures/rooms/PoolsideExterior.jpg' />",
		"<img data-name='POOLSIDE ROOM' data-description='The #1 choice of smart shoppers - spacious and comfortable (sleeps 2 adults and 2 children), great for making new friends, and $60 less than the Waters Edge room' src='./pbayImages/Pictures/rooms/PoolsideRoom.jpg' />",
		"<img data-name='QUANTUM VILLA' data-description='This suite is the venue of choice for days-long family reunions, and small corporate huddles.' src='./pbayImages/Pictures/rooms/QuantumVilla.jpg' />",
		"<img data-name='SPA IMMERSION ROOM AND PACKAGE' data-description='For spa aficionados' src='./pbayImages/Pictures/rooms/SpaIndulgenceRoom.jpg' />",
		"<img data-name='TWO BEDROOM SUITE' data-description='Most preferred by two couples vacationing together, or larger families with several children.' src='./pbayImages/Pictures/rooms/TwoBedroomSuite.jpg' />",
		"<img data-name='WATERS EDGE ROOM' data-description='A top choice for couples seeking something more special and romantic.' src='./pbayImages/Pictures/rooms/WatersEdgeExterior.jpg' />",
		"<img data-name='WATERS EDGE ROOM' data-description='A top choice for couples seeking something more special and romantic.' src='./pbayImages/Pictures/rooms/WatersEdgeRoom1.jpg' />",
		"<img data-name='WATERS EDGE ROOM' data-description='A top choice for couples seeking something more special and romantic.' src='./pbayImages/Pictures/rooms/WatersEdgeRoom2.jpg' />"

		// "<img title='' description='' src='' data-src='./pbayImages/Pictures/rooms/LagoonSideRoom.jpg' />",
		// "<img title='' description='' src='' data-src='./pbayImages/Pictures/rooms/LagoonSideTerrace.jpg' />",
		// "<img title='' description='' src='' data-src='./pbayImages/Pictures/rooms/LagoonViewRoom.jpg' />",
		// "<img title='' description='' src='' data-src='./pbayImages/Pictures/rooms/LagoonViewTerrace.jpg' />",
		// "<img title='' description='' src='' data-src='./pbayImages/Pictures/rooms/OneBedroomSuite.jpg' />",
		// "<img title='' description='' src='' data-src='./pbayImages/Pictures/rooms/OneBedroomSuite2.jpg' />",
		// "<img title='' description='' src='' data-src='./pbayImages/Pictures/rooms/OneBedroomSuite3.jpg' />",
		// "<img title='' description='' src='' data-src='./pbayImages/Pictures/rooms/PoolsideExterior.jpg' />",
		// "<img title='' description='' src='' data-src='./pbayImages/Pictures/rooms/PoolsideRoom.jpg' />",
		// "<img title='' description='' src='' data-src='./pbayImages/Pictures/rooms/QuantumVilla.jpg' />",
		// "<img title='' description='' src='' data-src='./pbayImages/Pictures/rooms/SpaIndulgenceRoom.jpg' />",
		// "<img title='' description='' src='' data-src='./pbayImages/Pictures/rooms/TwoBedroomSuite.jpg' />",
		// "<img title='' description='' src='' data-src='./pbayImages/Pictures/rooms/WatersEdgeExterior.jpg' />",
		// "<img title='' description='' src='' data-src='./pbayImages/Pictures/rooms/WatersEdgeRoom1.jpg' />",
		// "<img title='' description='' src='' data-src='./pbayImages/Pictures/rooms/WatersEdgeRoom2.jpg' />"
];

var restaurantsImgUrls = [
		"<img title='' description='' src='./pbayImages/Pictures/restaurants/AlienAbduction1.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/restaurants/AlienAbduction2.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/restaurants/AlienAbduction3.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/restaurants/AlienAbduction3SodaFountain.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/restaurants/FijiRestaurant.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/restaurants/FijiRestaurant2.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/restaurants/FijiRestaurant3.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/restaurants/KilimanjaroKafe2.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/restaurants/OpenDinnerBuffet-ArabianNights.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/restaurants/OpenDinnerBuffet-ArabianNights2.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/restaurants/OpenDinnerBuffet-Brazilian.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/restaurants/OpenDinnerBuffet-Brazilian2.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/restaurants/OpenDinnerBuffet-FilipinoFiesta.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/restaurants/OpenDinnerBuffet-FilipinoFiesta1.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/restaurants/OpenDinnerBuffet-HawaiianLuau.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/restaurants/OpenDinnerBuffet-RockinUSA.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/restaurants/OpenDinnerBuffet-RockinUSA2.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/restaurants/OpenDinnerBuffet-VivaEspaña.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/restaurants/OpenDinnerBuffet-VivaEspaña2.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/restaurants/PalermoTapasandPastaBar.jpg' />"
];

var landscapesImgUrls = [
		"<img title='' description='' src='./pbayImages/Pictures/landscape/Children.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/landscape/Gazebodd.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/landscape/KilimanjaroPool.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/landscape/KilimanjaroPool2.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/landscape/KilimanjaroPool3.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/landscape/Landcsape.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/landscape/Landscape2.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/landscape/Lobby.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/landscape/PBbeach.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/landscape/PBwharf.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/landscape/PeninsulaBeach1.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/landscape/PeninsulaBeach2.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/landscape/PeninsulaBeach3.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/landscape/Romantic1.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/landscape/Romantic2.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/landscape/Signature-EastLagoon.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/landscape/Signature.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/landscape/UndertreeCottage.jpg' />"
];

var activitiesImgUrls = [
		"<img title='' description='' src='./pbayImages/Pictures/activities/Archery2.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/activities/BananaBoat.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/activities/BananaBoat1.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/activities/BananaBoat2.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/activities/BigBuckSafari.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/activities/BukoBar.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/activities/Cart.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/activities/ChildrensCenter.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/activities/ChildrensCenter2.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/activities/ChildrensPlayground.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/activities/ChildrensPlayground2.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/activities/CustomizeYourOwnFlipFlops.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/activities/Diverock.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/activities/Diving.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/activities/Family1.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/activities/Family2.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/activities/Family3.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/activities/Family4.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/activities/Fishing.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/activities/Gameroom.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/activities/Gameroom2.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/activities/Halo-HaloMaking.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/activities/HobieCat1.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/activities/HobieCat2.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/activities/HobieCat3.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/activities/In-doorFiringRange.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/activities/IslandHopping.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/activities/KalesaRide.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/activities/KalesaRide2.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/activities/Kayak.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/activities/Kayak1.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/activities/Kayak2.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/activities/kayaking.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/activities/Kayaking2.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/activities/KayakingChildren.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/activities/MogamboFalls.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/activities/NailArt.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/activities/Parasailing.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/activities/PitchandPutt.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/activities/PitchPutt.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/activities/RomanticRoom Setup.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/activities/S8.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/activities/Salon.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/activities/Segway.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/activities/Segway2.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/activities/Segway3.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/activities/StandUpPaddle.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/activities/StandUpPaddle2.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/activities/SunsetCruise.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/activities/SUPYoga.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/activities/SUPYoga2.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/activities/TableTennis.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/activities/TandemBike.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/activities/TandemBike2.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/activities/TandemBike3.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/activities/Tennis.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/activities/Tennis2.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/activities/Tennis3.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/activities/Volleyball.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/activities/Wakeboarding.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/activities/WallClimbing.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/activities/WallClimbing1.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/activities/WallClimbing2.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/activities/WallCLimbing3.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/activities/WaterRoller.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/activities/WaterVolleyball.jpg' />"
];

var mogambospringsImgUrls = [
		"<img title='' description='' src='./pbayImages/Pictures/mogambosprings/MogamboSprings2.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/mogambosprings/MogamboSprings3.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/mogambosprings/MogamboSprings4.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/mogambosprings/MogamboSprings5.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/mogambosprings/MogamboSprings7.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/mogambosprings/MogamboSprings8.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/mogambosprings/MogamboSpringslogo.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/mogambosprings/PlantationBay2014-449.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/mogambosprings/PlantationBay2014-470.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/mogambosprings/Spa1.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/mogambosprings/Spa2.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/mogambosprings/Spa3.jpg' />"
];

var weddingsImgUrls = [
		"<img title='' description='' src='./pbayImages/Pictures/weddings/2.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/weddings/4.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/weddings/5.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/weddings/13.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/weddings/Romantic1.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/weddings/Romantic2.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/weddings/Romantic3.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/weddings/Romantic4.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/weddings/Wedding1.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/weddings/Wedding2.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/weddings/Wedding3.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/weddings/Wedding4.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/weddings/Wedding5.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/weddings/Wedding6.jpg' />",
		"<img title='' description='' src='./pbayImages/Pictures/weddings/Wedding7.jpg' />"
];