// var roomsImgUrls = [];


var roomsImgUrls = [
		"./pbayImages/rooms/1bedroomsuite.jpg",
		"./pbayImages/rooms/2bedroomsuite.jpg",
		"./pbayImages/rooms/familyroom.jpg",
		"./pbayImages/rooms/lagoonside_nile.jpg",
		"./pbayImages/rooms/lagoonview.jpg",
		"./pbayImages/rooms/poolsideroom.jpg",
		"./pbayImages/rooms/quantumvilla.jpg",
		"./pbayImages/rooms/spaindulgenceroom.jpg",
		"./pbayImages/rooms/watersedge.jpg",
		"./pbayImages/rooms/riverboatsuite.jpg",
		"./pbayImages/Pictures/rooms/LagoonSideRoom.jpg",
		"./pbayImages/Pictures/rooms/LagoonSideTerrace.jpg",
		"./pbayImages/Pictures/rooms/LagoonViewRoom.jpg",
		"./pbayImages/Pictures/rooms/LagoonViewTerrace.jpg",
		"./pbayImages/Pictures/rooms/OneBedroomSuite.jpg",
		"./pbayImages/Pictures/rooms/OneBedroomSuite2.jpg",
		"./pbayImages/Pictures/rooms/OneBedroomSuite3.jpg",
		"./pbayImages/Pictures/rooms/PoolsideExterior.jpg",
		"./pbayImages/Pictures/rooms/PoolsideRoom.jpg",
		"./pbayImages/Pictures/rooms/QuantumVilla.jpg",
		"./pbayImages/Pictures/rooms/SpaIndulgenceRoom.jpg",
		"./pbayImages/Pictures/rooms/TwoBedroomSuite.jpg",
		"./pbayImages/Pictures/rooms/WatersEdgeExterior.jpg",
		"./pbayImages/Pictures/rooms/WatersEdgeRoom1.jpg",
		"./pbayImages/Pictures/rooms/WatersEdgeRoom2.jpg"
		// "<img data-name='LAGOON SIDE ROOM' data-description='Preferred by couples and smaller families who want to be close to the lagoon. Our most popular room.' src='./images/spinner.gif' data-src='./pbayImages/Pictures/rooms/LagoonSideRoom.jpg' />",
		// "<img data-name='LAGOON SIDE ROOM' data-description='Preferred by couples and smaller families who want to be close to the lagoon. Our most popular room.' src='./images/spinner.gif' data-src='./pbayImages/Pictures/rooms/LagoonSideTerrace.jpg' />",
		// "<img data-name='LAGOON VIEW ROOM' data-description='Exactly the same room and amenities as a Lagoon Side room, with a better view in fact, but just a little farther from the lagoon.' src='./images/spinner.gif' data-src='./pbayImages/Pictures/rooms/LagoonViewRoom.jpg' />",
		// "<img data-name='LAGOON VIEW ROOM' data-description='Exactly the same room and amenities as a Lagoon Side room, with a better view in fact, but just a little farther from the lagoon.' src='./images/spinner.gif' data-src='./pbayImages/Pictures/rooms/LagoonViewTerrace.jpg' />",
		// "<img data-name='ONE BEDROOM SUITE' data-description='For parents with one or two older children, or executives who need space to work or entertain.' src='./images/spinner.gif' data-src='./pbayImages/Pictures/rooms/OneBedroomSuite.jpg' />",
		// "<img data-name='ONE BEDROOM SUITE' data-description='For parents with one or two older children, or executives who need space to work or entertain.' src='./images/spinner.gif' data-src='./pbayImages/Pictures/rooms/OneBedroomSuite2.jpg' />",
		// "<img data-name='ONE BEDROOM SUITE' data-description='For parents with one or two older children, or executives who need space to work or entertain.' src='./images/spinner.gif' data-src='./pbayImages/Pictures/rooms/OneBedroomSuite3.jpg' />",
		// "<img data-name='POOLSIDE ROOM' data-description='The #1 choice of smart shoppers - spacious and comfortable (sleeps 2 adults and 2 children), great for making new friends, and $60 less than the Waters Edge room' src='./images/spinner.gif' data-src='./pbayImages/Pictures/rooms/PoolsideExterior.jpg' />",
		// "<img data-name='POOLSIDE ROOM' data-description='The #1 choice of smart shoppers - spacious and comfortable (sleeps 2 adults and 2 children), great for making new friends, and $60 less than the Waters Edge room' src='./images/spinner.gif' data-src='./pbayImages/Pictures/rooms/PoolsideRoom.jpg' />",
		// "<img data-name='QUANTUM VILLA' data-description='This suite is the venue of choice for days-long family reunions, and small corporate huddles.' src='./images/spinner.gif' data-src='./pbayImages/Pictures/rooms/QuantumVilla.jpg' />",
		// "<img data-name='SPA IMMERSION ROOM AND PACKAGE' data-description='For spa aficionados' src='./images/spinner.gif' data-src='./pbayImages/Pictures/rooms/SpaIndulgenceRoom.jpg' />",
		// "<img data-name='TWO BEDROOM SUITE' data-description='Most preferred by two couples vacationing together, or larger families with several children.' src='./images/spinner.gif' data-src='./pbayImages/Pictures/rooms/TwoBedroomSuite.jpg' />",
		// "<img data-name='WATERS EDGE ROOM' data-description='A top choice for couples seeking something more special and romantic.' src='./images/spinner.gif' data-src='./pbayImages/Pictures/rooms/WatersEdgeExterior.jpg' />",
		// "<img data-name='WATERS EDGE ROOM' data-description='A top choice for couples seeking something more special and romantic.' src='./images/spinner.gif' data-src='./pbayImages/Pictures/rooms/WatersEdgeRoom1.jpg' />",
		// "<img data-name='WATERS EDGE ROOM' data-description='A top choice for couples seeking something more special and romantic.'  src='./images/spinner.gif' data-src='./pbayImages/Pictures/rooms/WatersEdgeRoom2.jpg' />"
];

var restaurantsImgUrls = [
		"./pbayImages/Pictures/restaurants/AlienAbduction1.jpg",
		"./pbayImages/Pictures/restaurants/AlienAbduction2.jpg",
		"./pbayImages/Pictures/restaurants/AlienAbduction3.jpg",
		"./pbayImages/Pictures/restaurants/AlienAbduction3SodaFountain.jpg",
		"./pbayImages/Pictures/restaurants/FijiRestaurant.jpg",
		"./pbayImages/Pictures/restaurants/FijiRestaurant2.jpg",
		"./pbayImages/Pictures/restaurants/FijiRestaurant3.jpg",
		"./pbayImages/Pictures/restaurants/KilimanjaroKafe2.jpg",
		"./pbayImages/Pictures/restaurants/OpenDinnerBuffet-ArabianNights.jpg",
		"./pbayImages/Pictures/restaurants/OpenDinnerBuffet-ArabianNights2.jpg",
		"./pbayImages/Pictures/restaurants/OpenDinnerBuffet-Brazilian.jpg",
		"./pbayImages/Pictures/restaurants/OpenDinnerBuffet-Brazilian2.jpg",
		"./pbayImages/Pictures/restaurants/OpenDinnerBuffet-FilipinoFiesta.jpg",
		"./pbayImages/Pictures/restaurants/OpenDinnerBuffet-FilipinoFiesta1.jpg",
		"./pbayImages/Pictures/restaurants/OpenDinnerBuffet-HawaiianLuau.jpg",
		"./pbayImages/Pictures/restaurants/OpenDinnerBuffet-RockinUSA.jpg",
		"./pbayImages/Pictures/restaurants/OpenDinnerBuffet-RockinUSA2.jpg",
		"./pbayImages/Pictures/restaurants/OpenDinnerBuffet-VivaEspaña.jpg",
		"./pbayImages/Pictures/restaurants/OpenDinnerBuffet-VivaEspaña2.jpg",
		"./pbayImages/Pictures/restaurants/PalermoTapasandPastaBar.jpg"
];

var landscapesImgUrls = [
		"./pbayImages/Pictures/landscape/Children.jpg",
		"./pbayImages/Pictures/landscape/Gazebodd.jpg",
		"./pbayImages/Pictures/landscape/KilimanjaroPool.jpg",
		"./pbayImages/Pictures/landscape/KilimanjaroPool2.jpg",
		"./pbayImages/Pictures/landscape/KilimanjaroPool3.jpg",
		"./pbayImages/Pictures/landscape/Landcsape.jpg",
		"./pbayImages/Pictures/landscape/Landscape2.jpg",
		"./pbayImages/Pictures/landscape/Lobby.jpg",
		"./pbayImages/Pictures/landscape/PBbeach.jpg",
		"./pbayImages/Pictures/landscape/PBwharf.jpg",
		"./pbayImages/Pictures/landscape/PeninsulaBeach1.jpg",
		"./pbayImages/Pictures/landscape/PeninsulaBeach2.jpg",
		"./pbayImages/Pictures/landscape/PeninsulaBeach3.jpg",
		"./pbayImages/Pictures/landscape/Romantic1.jpg",
		"./pbayImages/Pictures/landscape/Romantic2.jpg",
		"./pbayImages/Pictures/landscape/Signature-EastLagoon.jpg",
		"./pbayImages/Pictures/landscape/Signature.jpg",
		"./pbayImages/Pictures/landscape/UndertreeCottage.jpg"
];

var activitiesImgUrls = [
		"./pbayImages/Pictures/activities/Archery2.jpg",
		"./pbayImages/Pictures/activities/BananaBoat.jpg",
		"./pbayImages/Pictures/activities/BananaBoat1.jpg",
		"./pbayImages/Pictures/activities/BananaBoat2.jpg",
		"./pbayImages/Pictures/activities/BigBuckSafari.jpg",
		"./pbayImages/Pictures/activities/BukoBar.jpg",
		"./pbayImages/Pictures/activities/Cart.jpg",
		"./pbayImages/Pictures/activities/ChildrensCenter.jpg",
		"./pbayImages/Pictures/activities/ChildrensCenter2.jpg",
		"./pbayImages/Pictures/activities/ChildrensPlayground.jpg",
		"./pbayImages/Pictures/activities/ChildrensPlayground2.jpg",
		"./pbayImages/Pictures/activities/CustomizeYourOwnFlipFlops.jpg",
		"./pbayImages/Pictures/activities/Diverock.jpg",
		"./pbayImages/Pictures/activities/Diving.jpg",
		"./pbayImages/Pictures/activities/Family1.jpg",
		"./pbayImages/Pictures/activities/Family2.jpg",
		"./pbayImages/Pictures/activities/Family3.jpg",
		"./pbayImages/Pictures/activities/Family4.jpg",
		"./pbayImages/Pictures/activities/Fishing.jpg",
		"./pbayImages/Pictures/activities/Gameroom.jpg",
		"./pbayImages/Pictures/activities/Gameroom2.jpg",
		"./pbayImages/Pictures/activities/Halo-HaloMaking.jpg",
		"./pbayImages/Pictures/activities/HobieCat1.jpg",
		"./pbayImages/Pictures/activities/HobieCat2.jpg",
		"./pbayImages/Pictures/activities/HobieCat3.jpg",
		"./pbayImages/Pictures/activities/In-doorFiringRange.jpg",
		"./pbayImages/Pictures/activities/IslandHopping.jpg",
		"./pbayImages/Pictures/activities/KalesaRide.jpg",
		"./pbayImages/Pictures/activities/KalesaRide2.jpg",
		"./pbayImages/Pictures/activities/Kayak.jpg",
		"./pbayImages/Pictures/activities/Kayak1.jpg",
		"./pbayImages/Pictures/activities/Kayak2.jpg",
		"./pbayImages/Pictures/activities/kayaking.jpg",
		"./pbayImages/Pictures/activities/Kayaking2.jpg",
		"./pbayImages/Pictures/activities/KayakingChildren.jpg",
		"./pbayImages/Pictures/activities/MogamboFalls.jpg",
		"./pbayImages/Pictures/activities/NailArt.jpg",
		"./pbayImages/Pictures/activities/Parasailing.jpg",
		"./pbayImages/Pictures/activities/PitchandPutt.jpg",
		"./pbayImages/Pictures/activities/PitchPutt.jpg",
		"./pbayImages/Pictures/activities/RomanticRoom Setup.jpg",
		"./pbayImages/Pictures/activities/S8.jpg",
		"./pbayImages/Pictures/activities/Salon.jpg",
		"./pbayImages/Pictures/activities/Segway.jpg",
		"./pbayImages/Pictures/activities/Segway2.jpg",
		"./pbayImages/Pictures/activities/Segway3.jpg",
		"./pbayImages/Pictures/activities/StandUpPaddle.jpg",
		"./pbayImages/Pictures/activities/StandUpPaddle2.jpg",
		"./pbayImages/Pictures/activities/SunsetCruise.jpg",
		"./pbayImages/Pictures/activities/SUPYoga.jpg",
		"./pbayImages/Pictures/activities/SUPYoga2.jpg",
		"./pbayImages/Pictures/activities/TableTennis.jpg",
		"./pbayImages/Pictures/activities/TandemBike.jpg",
		"./pbayImages/Pictures/activities/TandemBike2.jpg",
		"./pbayImages/Pictures/activities/TandemBike3.jpg",
		"./pbayImages/Pictures/activities/Tennis.jpg",
		"./pbayImages/Pictures/activities/Tennis2.jpg",
		"./pbayImages/Pictures/activities/Tennis3.jpg",
		"./pbayImages/Pictures/activities/Volleyball.jpg",
		"./pbayImages/Pictures/activities/Wakeboarding.jpg",
		"./pbayImages/Pictures/activities/WallClimbing.jpg",
		"./pbayImages/Pictures/activities/WallClimbing1.jpg",
		"./pbayImages/Pictures/activities/WallClimbing2.jpg",
		"./pbayImages/Pictures/activities/WallCLimbing3.jpg",
		"./pbayImages/Pictures/activities/WaterRoller.jpg",
		"./pbayImages/Pictures/activities/WaterVolleyball.jpg"
];

var mogambospringsImgUrls = [
		"./pbayImages/Pictures/mogambosprings/MogamboSprings2.jpg",
		"./pbayImages/Pictures/mogambosprings/MogamboSprings3.jpg",
		"./pbayImages/Pictures/mogambosprings/MogamboSprings4.jpg",
		"./pbayImages/Pictures/mogambosprings/MogamboSprings5.jpg",
		"./pbayImages/Pictures/mogambosprings/MogamboSprings7.jpg",
		"./pbayImages/Pictures/mogambosprings/MogamboSprings8.jpg",
		"./pbayImages/Pictures/mogambosprings/MogamboSpringslogo.jpg",
		"./pbayImages/Pictures/mogambosprings/PlantationBay2014-449.jpg",
		"./pbayImages/Pictures/mogambosprings/PlantationBay2014-470.jpg",
		"./pbayImages/Pictures/mogambosprings/Spa1.jpg",
		"./pbayImages/Pictures/mogambosprings/Spa2.jpg",
		"./pbayImages/Pictures/mogambosprings/Spa3.jpg"
];

var weddingsImgUrls = [
		"./pbayImages/Pictures/weddings/2.jpg",
		"./pbayImages/Pictures/weddings/4.jpg",
		"./pbayImages/Pictures/weddings/5.jpg",
		"./pbayImages/Pictures/weddings/13.jpg",
		"./pbayImages/Pictures/weddings/Romantic1.jpg",
		"./pbayImages/Pictures/weddings/Romantic2.jpg",
		"./pbayImages/Pictures/weddings/Romantic3.jpg",
		"./pbayImages/Pictures/weddings/Romantic4.jpg",
		"./pbayImages/Pictures/weddings/Wedding1.jpg",
		"./pbayImages/Pictures/weddings/Wedding2.jpg",
		"./pbayImages/Pictures/weddings/Wedding3.jpg",
		"./pbayImages/Pictures/weddings/Wedding4.jpg",
		"./pbayImages/Pictures/weddings/Wedding5.jpg",
		"./pbayImages/Pictures/weddings/Wedding6.jpg",
		"./pbayImages/Pictures/weddings/Wedding7.jpg"
];